version: '3.8'

services:
  # O Banco de Dados
  mongodb:
    image: mongo:6.0
    container_name: meu-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=chatdb

  # O Zookeeper (O "Gerente" do Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: meu-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # O Kafka (O Carteiro)
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: meu-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1